Same dataset as main_para but uses pycaret (a python library) to have quick model training and comparison.

In [1]:
import pandas as pd
import numpy as np
import xgboost
from pycaret.regression import *

In [2]:
df = pd.read_csv('data/data_fcut.csv')

In [3]:
df_ = df[['duration',
'month_start', 'day_start', 'dayOfWeek_start', 'hour_start',
'month_end', 'day_end', 'dayOfWeek_end', 'hour_end', 
'lat_strt', 'lng_strt', 'lat_end', 'lng_end','statn_dist', 
'rain','status','status_end', 'municipal', 'municipal_end',
'strt_statn', 'end_statn','bike_nr','subsc_type',
]]

In [5]:
exp = setup(data=df_, target='duration', session_id=123,
            categorical_features=['rain', 'municipal','municipal_end','subsc_type'],
            numeric_features=['month_start', 'day_start', 'dayOfWeek_start', 'hour_start', 'month_end', 'day_end',
             'dayOfWeek_end', 'hour_end', 'lat_strt', 'lng_strt', 'lat_end', 'lng_end', 'statn_dist'],
            ignore_features=['status','status_end','strt_statn', 'end_statn','bike_nr'],
            fold=5,use_gpu=True)

In [9]:
best = compare_models()

In [10]:
rf = create_model('rf')

In [6]:
xgb = create_model('xgboost')

further cut on lower limit

In [5]:
df_2 = df_.query('duration > 60')
df_.shape[0],df_2.shape[0]

(1470266, 1462238)

In [6]:
exp = setup(data=df_2, target='duration', session_id=123,
            categorical_features=['rain', 'municipal','municipal_end','subsc_type'],
            numeric_features=['month_start', 'day_start', 'dayOfWeek_start', 'hour_start', 'month_end', 'day_end',
             'dayOfWeek_end', 'hour_end', 'lat_strt', 'lng_strt', 'lat_end', 'lng_end', 'statn_dist'],
            ignore_features=['status','status_end','strt_statn', 'end_statn','bike_nr'],
            fold=5,use_gpu=True)

In [38]:
best = compare_models(include=['lr','dt','rf','et'])

IntProgress(value=0, description='Processing: ', max=24)

Initiated  . . . . . . . . . . . . . . . . . .               10:01:29
Status     . . . . . . . . . . . . . . . . . .        Fitting 5 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extra Trees Regressor

In [15]:
best = compare_models(include=['lightgbm','gbr'])

In [9]:
rf = create_model('rf')

In [9]:
xgb = create_model('xgboost')

In [7]:
best = compare_models()

In [9]:
xgb_tuned = tune_model(xgboost)

ValueError: Estimator <module 'xgboost' from 'C:\\Users\\david\\anaconda3\\envs\\DSTest_pycaret\\lib\\site-packages\\xgboost\\__init__.py'> does not have the required fit() method.